//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcje
    {
        public int Id { get; set; }
        public int Id_dane { get; set; }
        public string Status { get; set; }
        public decimal Kwota { get; set; }
        public string Produkty { get; set; }
    
        public virtual Dane_Osobowe Dane_Osobowe { get; set; }
    }
}
