//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZProgramowania
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int Categoria_Id { get; set; }
        public string Opis { get; set; }
        public byte[] Img { get; set; }
        public decimal Cena { get; set; }
        public string Stan { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}
